apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: probes-pod
  name: probes-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - echo "Intai Dorm" && sleep 15 && touch /tmp/readiness && touch /tmp/liveness && echo 'Am create fisierele' && sleep Infinity  
    image: busybox
    name: readiness-container
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/readiness
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/liveness
      initialDelaySeconds: 5
      periodSeconds: 5