apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: readiness-pod
  name: readiness-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - echo "Intai dorm" && sleep 15 && touch /tmp/healthy && echo 'Am creat fisier' && sleep Infinity
    image: busybox
    name: readiness-container
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
