apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple
  name: simple-1
spec:
  containers:
  - image: andreimihai/simple-server:0.1.0
    name: simple
    resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple
  name: simple-2
spec:
  containers:
  - image: andreimihai/simple-server:0.1.0
    name: simple
    resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple
  name: simple-3
spec:
  containers:
  - image: andreimihai/simple-server:0.1.0
    name: simple
    resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: simple
  name: simple-service
spec:
  ports:
  - port: 8123
    protocol: TCP
    targetPort: 8123
  selector:
    run: simple
  type: LoadBalancer
status:
  loadBalancer: {}