apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple
  name: simple
spec:
  containers:
  - image: andreimihai/simple-server:0.1.0
    name: simple
    resources:
      requests:
        memory: "100Mi"
        cpu: "250m"
      limits:
        memory: "500Mi"
        cpu: "500m"