FROM ubuntu

# Evita intreractii cu utilizatorul
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
        apt-get install -y vim curl iputils-ping && \
	    apt-get clean

CMD ["sleep","infinity"]