version: '3.8'

services:
  blue:
    image: nginx
    container_name: blue
    volumes: 
      - ./blue-server:/usr/share/nginx/html

  green:
    image: nginx
    container_name: green
    volumes: 
      - ./green-server:/usr/share/nginx/html

  red: 
    image: nginx
    container_name: red
    volumes:
     - ./red-server:/usr/share/nginx/html

  loadbalancer:
    image: nginx
    container_name: loadbalancer
    ports: 
      - "8070:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf

  