apiVersion: v1
data:
  user_db: ZGItYWRtaW4=
  user_passwd: cGFyb2xhMTIz
kind: Secret
metadata:
  creationTimestamp: null
  name: secrets-db
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db-pod
  name: db-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - echo user=$user_db si password=$user_passwd && sleep 3600
    image: alpine
    name: db-pod-container
    envFrom:
    - secretRef:
        name: secrets-db
