apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine
    location: local-host
  name: alpine-pod
spec:
  containers:
  - command:
    - sh 
    - -c 
    - 'while true; do echo "$(date)" && sleep 3; done'
    image: alpine
    name: alpine-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
