apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine
    location: local-host
  name: alpine-pod
spec:
  containers:
  - command:
    - sleep
    - '30'
    image: alpine
    name: alpine-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
